spring:
  data:
    redis:
      host: host.docker.internal
      port: 6379

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/HPCLab
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace