spring:
  sql:
    init:
      mode: never

  data:
    redis:
      host: 172.17.0.6
      port: 6379

  datasource:
    url: jdbc:postgresql://172.17.0.5:5432/HPCLab
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace