-- Admin
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'HPCLab@csatmaker.site', '$2b$12$s2OijpjdlsHCxljIQyLQOumu5s9M6ivgAbqVCP9BGOk9xn5ACw1g6', 0,'Admin');
INSERT INTO BOOK(EMAIL) VALUES ('HPCLab@csatmaker.site');

-- 지도교수
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'ejung@hongik.ac.kr', '$2a$10$8Fsj6GzBZPo.9FlH1tAug.3gOljelRAWNpVAGu8koYjOIoydh39aO', 0,'지도교수');
INSERT INTO BOOK(EMAIL) VALUES ('ejung@hongik.ac.kr');

-- Test1
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'a@b.c', '$2b$12$dZkRhFZJnpULWyMsl2zLhulrG/lXefzdYeKFP3q48awnxJ/Xd/6om', 2,'잠자는 거북이');
INSERT INTO BOOK(EMAIL) VALUES ('a@b.c');

-- Test2
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'd@e.f', '$2b$12$ZX1YeIO4wKKsjEptkxhg1OtB.a.EmG7N5pTqvvYnjF3fjBRcInamS', 2,'달리는 토끼');
INSERT INTO BOOK(EMAIL) VALUES ('d@e.f');

-- Test3
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'g@h.i', '$2b$12$OHMydPVw.g3hkARPDnoVBOhsvdeJqsQq/PPi9W6knAGcu6tHkhJMa', 2,'웃는 강아지');
INSERT INTO BOOK(EMAIL) VALUES ('g@h.i');